typography_spectrum: 0.1047261
color:
  saturation: 0.2285587738733739
  brandStrength: 0.9900615853257477
  rhythmicContrast: 0.9134283310268074
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  lightness: 0.823190136346966
layout_spectrum: 0.9564983
author:
  name: Dave McCutcheon
  email: dave@thecollectioncorner.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/68122077-f70d-4c5e-9feb-8b8695dd12a2.jpg
name: The Collection Corner
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a3396a45-88d3-41d1-b14e-0eab93c62044.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Custom LED lighting and Accessories
description: >-
  Hand Crafted, Custom LED Lighting, Signs and Accessories to Enhance Your
  Display of Collectibles.
